process.env.TS_NODE_PROJECT="tests/bdd/tsconfig.json";
module.exports={
    default:{
        requireModule:['ts-node/register'],
        require:['tests/bdd/steps/**/*.ts','tests/bdd/support/**/*.ts'],
        paths:['tests/bdd/features/**/*.feature'],
        format:['html:cucumber-report.html'],
    },
};